// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/pb/gchat.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConnectToChatRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToChatRequest) Reset()         { *m = ConnectToChatRequest{} }
func (m *ConnectToChatRequest) String() string { return proto.CompactTextString(m) }
func (*ConnectToChatRequest) ProtoMessage()    {}
func (*ConnectToChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41191c10035d7058, []int{0}
}

func (m *ConnectToChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToChatRequest.Unmarshal(m, b)
}
func (m *ConnectToChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToChatRequest.Marshal(b, m, deterministic)
}
func (m *ConnectToChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToChatRequest.Merge(m, src)
}
func (m *ConnectToChatRequest) XXX_Size() int {
	return xxx_messageInfo_ConnectToChatRequest.Size(m)
}
func (m *ConnectToChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToChatRequest proto.InternalMessageInfo

func (m *ConnectToChatRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ConnectToChatResponse struct {
	Response             string   `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConnectToChatResponse) Reset()         { *m = ConnectToChatResponse{} }
func (m *ConnectToChatResponse) String() string { return proto.CompactTextString(m) }
func (*ConnectToChatResponse) ProtoMessage()    {}
func (*ConnectToChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41191c10035d7058, []int{1}
}

func (m *ConnectToChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectToChatResponse.Unmarshal(m, b)
}
func (m *ConnectToChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectToChatResponse.Marshal(b, m, deterministic)
}
func (m *ConnectToChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectToChatResponse.Merge(m, src)
}
func (m *ConnectToChatResponse) XXX_Size() int {
	return xxx_messageInfo_ConnectToChatResponse.Size(m)
}
func (m *ConnectToChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectToChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectToChatResponse proto.InternalMessageInfo

func (m *ConnectToChatResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

type ChatMessage struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatMessage) Reset()         { *m = ChatMessage{} }
func (m *ChatMessage) String() string { return proto.CompactTextString(m) }
func (*ChatMessage) ProtoMessage()    {}
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_41191c10035d7058, []int{2}
}

func (m *ChatMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatMessage.Unmarshal(m, b)
}
func (m *ChatMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatMessage.Marshal(b, m, deterministic)
}
func (m *ChatMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatMessage.Merge(m, src)
}
func (m *ChatMessage) XXX_Size() int {
	return xxx_messageInfo_ChatMessage.Size(m)
}
func (m *ChatMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatMessage.DiscardUnknown(m)
}

var xxx_messageInfo_ChatMessage proto.InternalMessageInfo

func (m *ChatMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ChatMessage) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ChatRequest struct {
	Message              *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatRequest) Reset()         { *m = ChatRequest{} }
func (m *ChatRequest) String() string { return proto.CompactTextString(m) }
func (*ChatRequest) ProtoMessage()    {}
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41191c10035d7058, []int{3}
}

func (m *ChatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatRequest.Unmarshal(m, b)
}
func (m *ChatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatRequest.Marshal(b, m, deterministic)
}
func (m *ChatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatRequest.Merge(m, src)
}
func (m *ChatRequest) XXX_Size() int {
	return xxx_messageInfo_ChatRequest.Size(m)
}
func (m *ChatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChatRequest proto.InternalMessageInfo

func (m *ChatRequest) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

type ChatResponse struct {
	Message              *ChatMessage `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ChatResponse) Reset()         { *m = ChatResponse{} }
func (m *ChatResponse) String() string { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()    {}
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41191c10035d7058, []int{4}
}

func (m *ChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatResponse.Unmarshal(m, b)
}
func (m *ChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatResponse.Marshal(b, m, deterministic)
}
func (m *ChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatResponse.Merge(m, src)
}
func (m *ChatResponse) XXX_Size() int {
	return xxx_messageInfo_ChatResponse.Size(m)
}
func (m *ChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatResponse proto.InternalMessageInfo

func (m *ChatResponse) GetMessage() *ChatMessage {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*ConnectToChatRequest)(nil), "gchat.ConnectToChatRequest")
	proto.RegisterType((*ConnectToChatResponse)(nil), "gchat.ConnectToChatResponse")
	proto.RegisterType((*ChatMessage)(nil), "gchat.ChatMessage")
	proto.RegisterType((*ChatRequest)(nil), "gchat.ChatRequest")
	proto.RegisterType((*ChatResponse)(nil), "gchat.ChatResponse")
}

func init() { proto.RegisterFile("pkg/pb/gchat.proto", fileDescriptor_41191c10035d7058) }

var fileDescriptor_41191c10035d7058 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0xc8, 0x4e, 0xd7,
	0x2f, 0x48, 0xd2, 0x4f, 0x4f, 0xce, 0x48, 0x2c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x05, 0x73, 0x94, 0x8c, 0xb8, 0x44, 0x9c, 0xf3, 0xf3, 0xf2, 0x52, 0x93, 0x4b, 0x42, 0xf2, 0x9d,
	0x33, 0x12, 0x4b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x4a, 0x8b,
	0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x25,
	0x63, 0x2e, 0x51, 0x34, 0x3d, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x20, 0x4d, 0x45, 0x50, 0x36,
	0x4c, 0x13, 0x8c, 0xaf, 0xe4, 0xcc, 0xc5, 0x0d, 0x52, 0xeb, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e,
	0x8a, 0xcf, 0x7c, 0x21, 0x09, 0x2e, 0xf6, 0xe4, 0xfc, 0xbc, 0x92, 0xd4, 0xbc, 0x12, 0x09, 0x26,
	0xb0, 0x14, 0x8c, 0xab, 0x64, 0x0d, 0x31, 0x04, 0xe6, 0x48, 0x1d, 0x2e, 0xf6, 0x5c, 0x88, 0x79,
	0x60, 0x33, 0xb8, 0x8d, 0x84, 0xf4, 0x20, 0x5e, 0x44, 0xb2, 0x29, 0x08, 0xa6, 0x44, 0xc9, 0x86,
	0x8b, 0x07, 0xc5, 0xb5, 0x24, 0xe9, 0x36, 0x9a, 0xc4, 0x08, 0xb1, 0x3b, 0x38, 0xb5, 0xa8, 0x2c,
	0x33, 0x39, 0x55, 0xc8, 0x87, 0x8b, 0x17, 0x25, 0x10, 0x84, 0xa4, 0x61, 0xba, 0xb1, 0x04, 0xa7,
	0x94, 0x0c, 0x76, 0x49, 0x68, 0xd8, 0x30, 0x08, 0x99, 0x72, 0xb1, 0x80, 0x0d, 0x41, 0x76, 0x02,
	0x4c, 0xaf, 0x30, 0x8a, 0x18, 0x4c, 0x8b, 0x06, 0xa3, 0x01, 0xa3, 0x13, 0x4b, 0x14, 0x53, 0x41,
	0x52, 0x12, 0x1b, 0x38, 0x46, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59, 0xc2, 0xa2, 0x39,
	0xe7, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ChatServiceClient interface {
	ConnectToChat(ctx context.Context, in *ConnectToChatRequest, opts ...grpc.CallOption) (*ConnectToChatResponse, error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (ChatService_ChatClient, error)
}

type chatServiceClient struct {
	cc *grpc.ClientConn
}

func NewChatServiceClient(cc *grpc.ClientConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) ConnectToChat(ctx context.Context, in *ConnectToChatRequest, opts ...grpc.CallOption) (*ConnectToChatResponse, error) {
	out := new(ConnectToChatResponse)
	err := c.cc.Invoke(ctx, "/gchat.ChatService/ConnectToChat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (ChatService_ChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ChatService_serviceDesc.Streams[0], "/gchat.ChatService/Chat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatServiceChatClient{stream}
	return x, nil
}

type ChatService_ChatClient interface {
	Send(*ChatRequest) error
	Recv() (*ChatResponse, error)
	grpc.ClientStream
}

type chatServiceChatClient struct {
	grpc.ClientStream
}

func (x *chatServiceChatClient) Send(m *ChatRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatServiceChatClient) Recv() (*ChatResponse, error) {
	m := new(ChatResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatServiceServer is the server API for ChatService service.
type ChatServiceServer interface {
	ConnectToChat(context.Context, *ConnectToChatRequest) (*ConnectToChatResponse, error)
	Chat(ChatService_ChatServer) error
}

// UnimplementedChatServiceServer can be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
}

func (*UnimplementedChatServiceServer) ConnectToChat(ctx context.Context, req *ConnectToChatRequest) (*ConnectToChatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConnectToChat not implemented")
}
func (*UnimplementedChatServiceServer) Chat(srv ChatService_ChatServer) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}

func RegisterChatServiceServer(s *grpc.Server, srv ChatServiceServer) {
	s.RegisterService(&_ChatService_serviceDesc, srv)
}

func _ChatService_ConnectToChat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectToChatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatServiceServer).ConnectToChat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gchat.ChatService/ConnectToChat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatServiceServer).ConnectToChat(ctx, req.(*ConnectToChatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatService_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatServiceServer).Chat(&chatServiceChatServer{stream})
}

type ChatService_ChatServer interface {
	Send(*ChatResponse) error
	Recv() (*ChatRequest, error)
	grpc.ServerStream
}

type chatServiceChatServer struct {
	grpc.ServerStream
}

func (x *chatServiceChatServer) Send(m *ChatResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatServiceChatServer) Recv() (*ChatRequest, error) {
	m := new(ChatRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ChatService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gchat.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectToChat",
			Handler:    _ChatService_ConnectToChat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _ChatService_Chat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/pb/gchat.proto",
}
